### ISSUE TITLE
Native error on Android 13: VIForegroundService: Foreground service is not started

### ISSUE THREAD

**Issue by vineus** [voximplant/react-native-foreground-service#57]
version: 

```
    "@voximplant/react-native-foreground-service": "3.0.2",
```

Android version: Android 13, build TQ1A.230105.002

when calling:

```typescript
        await VIForegroundService.getInstance().startService({
          channelId: ANDROID_NOTIFICATION_CHANNEL_ID,
          id: 101,
          title: "title",
          text: "text",
          icon: "ic_launcher",
        });
```

```
VIForegroundService: Foreground service is not started
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:106:50 in promiseMethodWrapper
at node_modules/@voximplant/react-native-foreground-service/index.js:92:4 in VIForegroundService#startService
at /tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:8 in tryCallTwo
at /tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:24 in doResolve
at /tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:13 in Promise
at node_modules/@voximplant/react-native-foreground-service/index.js:79:4 in VIForegroundService#createNotificationChannel
at  [redacted]
at /tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:8 in tryCallTwo
at /tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:24 in doResolve
at /tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:13 in Promise
at [redacted]
at  [redacted]
- ... 17 more stack frames from framework internals
```

Notification permission granted on the app

**Comment by vineus** [comment]
Answering my own question: service was missing from the manifest 🤦

**Comment by alexzborovskii** [comment]
@vineus thank you for your comment! it saved me a lot of time :)
